# A plain, Byobu like configuration

# --- Behavior ---
set -g extended-keys-format csi-u # Fix pi warning
set -g extended-keys on
set -g history-limit 10000
set -g mouse on

# --- Pane borders ---
set -g pane-border-lines heavy
set -g pane-border-style fg=colour240       # inactive panes
set -g pane-active-border-style fg=#e5c07b  # active pane

# --- Keybindings ---
# Window Management
bind-key -n F2      new-window -c "#{pane_current_path}" # New window
bind-key -n F3      previous-window                     # Previous window
bind-key -n F4      next-window                         # Next window

# Pane Management
bind-key -n C-F2    split-window -h -c "#{pane_current_path}" # Split horizontal
bind-key -n S-F2    split-window -v -c "#{pane_current_path}" # Split vertical
bind-key -n S-F11   resize-pane -Z                          # Zoom pane

# Pane Navigation
bind-key -n S-Up    select-pane -U
bind-key -n S-Down  select-pane -D
bind-key -n S-Left  select-pane -L
bind-key -n S-Right select-pane -R

# --- Clipboard ---
# On mouse release, copy selection to system clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
